### ISSUE TITLE
i test done but i create new test after false. Please explain me,  thank you verry much 

### ISSUE THREAD

**Issue by Nghiait123456** [mattiasgeniar/demo-php-blocking-sessions#2]
@mattiasgeniar  i edit file ajax_nonblocking_request.php  with content:
" <?php

// Open the session
session_name('nonblocking_sessions');
session_start();

// Release the session lock: behold, fast ajax calls!
// (just don't try to write to the session after this, changes will be lost)
session_write_close();

// Do all the application logic: call 3rd party APIs, do queries,
// run all kind of wrong ORM-for-loops, ...
echo "date1=".date("d-m-Y h:i:s");
sleep(10);
echo  "date2=".date("d-m-Y h:i:s");

// And done!
// No need to explicitly close the session, that's done automatically.

?> "

i used one brower with 2 tab   run file almost at the same time  for test timing log in echo "date1=".date("d-m-Y h:i:s"); and echo  "date2=".date("d-m-Y h:i:s");   .  But alway one request return first, request other wait faster request done for start. Image illustration:   

i get link http://localhost/ajax_nonblocking_request.php for test:, result:

date1=25-02-2020 11:05:16date2=25-02-2020 11:05:26 ( fast)
date1=25-02-2020 11:05:26date2=25-02-2020 11:05:36 (slow , wait one by one )
i don't share illustration, please help me

**Comment by Nghiait123456** [comment]
i call link  http://localhost/ajax_nonblocking_request.php  for test:, result:
1) date1=25-02-2020 11:05:16date2=25-02-2020 11:05:26 ( fast)
2) date1=25-02-2020 11:05:26date2=25-02-2020 11:05:36

i don't share illustration, please help me

**Comment by mattiasgeniar** [comment]
Hey,

Sorry, can't really offer any help on this, if you can't simulate it it could be that your sessions are configured differently than mine.

Mattias

**Comment by Nghiait123456** [comment]
@mattiasgeniar 
I guessed the problem with the php and apache configuration because I tested with the js pass. Can you share the configuration in your demo, php.ini and the files you think affect. It will be of great help to me and others in case of test failse.

A little bit marginal is that your configuration runs my example, and using 2 tabs in the browser to test the result, if failse then this is a problem worth investigating. Can you share the php.ini configuration file and test results in my case, it might give me a lot of clues.
  Thanks so much, many thanks

**Comment by Nghiait123456** [comment]
Cause of a problem due to chrome not work session_write_close (), or chorme load file,  I give it to anyone who needs it, the specific reason I will investigate further
